include: package:flutter_lints/flutter.yaml

linter:
  # https://dart-lang.github.io/linter/lints/index.html.
  # https://dart.dev/guides/language/analysis-options
  rules:
    close_sinks: true
    prefer_final_fields: true
    prefer_final_locals: true  
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    prefer_single_quotes: true
    annotate_overrides: true
    annotate_redeclares: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    always_use_package_imports: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    avoid_annotating_with_dynamic: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    prefer_adjacent_string_concatenation: true
    avoid_null_checks_in_equality_operators: true
    prefer_interpolation_to_compose_strings: true
    prefer_const_literals_to_create_immutables: true
