// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `delete_playlist_from_db`, `folder_key`, `get_all_playlists_from_db`, `get_all_songs_from_db`, `get_music_folders_from_db`, `get_playlist_from_db`, `get_playlist_tree`, `get_settings_tree`, `get_song_art_from_db`, `get_song_art_tree`, `get_song_tree`, `next_playlist_id`, `open_or_fetch_tree`, `playlist_key`, `remove_all_songs_from_db`, `remove_music_folder_from_db`, `remove_playlist_entry_from_db`, `remove_song_from_db`, `save_music_folder_to_db`, `save_playlist_entry_to_db`, `save_playlist_order_to_db`, `save_playlist_to_db`, `save_song_art_to_db`, `save_song_to_db`, `save_songs_to_db_bulk`, `set_db_dir`, `song_key`, `update_playlist_name_in_db`

/// Call from Flutter's AppLifecycleState.paused to guarantee durability
/// before Android kills the process. Covers any writes not yet flushed
/// by a bulk operation.
Future<void> flushDb() =>
    RustLib.instance.api.crateApiUtilsDatabaseOpsFlushDb();
