// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `folder_key`, `get_all_playlists_from_db`, `get_all_songs_from_db`, `get_music_folders_from_db`, `get_playlist_from_db`, `get_playlist_tree`, `get_settings_tree`, `get_song_tree`, `open_or_fetch_tree`, `playlist_key`, `remove_music_folder_from_db`, `remove_song_from_db`, `save_music_folder_to_db`, `save_playlist_to_db`, `save_song_to_db`, `song_key`

Future<void> setDbDir({required String dbDir}) =>
    RustLib.instance.api.crateApiUtilsDatabaseOpsSetDbDir(dbDir: dbDir);
