// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:music_player/src/rust/api/data/song.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MusicIndex>>
abstract class MusicIndex implements RustOpaqueInterface {
  Future<void> addSong({required Song song});

  Future<List<Song>> allSongs();

  Future<Song?> getSong({required BigInt id});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MusicIndex> newInstance({required String path}) =>
      RustLib.instance.api.crateApiDataMusicIndexMusicIndexNew(path: path);
}
