// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:music_player/src/rust/api/error/custom_error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:music_player/src/rust/api/data/song.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `borrow_decode`, `borrow_decode`, `clone`, `clone`, `decode`, `decode`, `encode`, `encode`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Playlist>>
abstract class Playlist implements RustOpaqueInterface {
  BigInt get id;

  String get name;

  Uint64List get songs;

  set id(BigInt id);

  set name(String name);

  set songs(Uint64List songs);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaylistCollection>>
abstract class PlaylistCollection implements RustOpaqueInterface {
  /// SongCollection struct
  /// PlaylistCollection struct
  /// PlayerState struct
  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<Playlist> addPlaylist({required String name});

  BigInt get defaultPlaylistId;

  Map<BigInt, Playlist> get playlistMap;

  set defaultPlaylistId(BigInt defaultPlaylistId);

  set playlistMap(Map<BigInt, Playlist> playlistMap);

  /// SongCollection struct
  /// PlaylistCollection struct
  /// PlayerState struct
  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<List<Playlist>> getAllPlaylists();

  /// SongCollection struct
  /// PlaylistCollection struct
  /// PlayerState struct
  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<List<Song>> getDefaultPlaylist();

  /// SongCollection struct
  /// PlaylistCollection struct
  /// PlayerState struct
  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<Playlist> getPlaylist({required BigInt playlistId});

  /// SongCollection struct
  /// PlaylistCollection struct
  /// PlayerState struct
  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  factory PlaylistCollection() =>
      RustLib.instance.api.crateApiDataPlaylistPlaylistCollectionNew();
}
