// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:music_player/src/rust/api/error/custom_error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `borrow_decode`, `borrow_decode`, `clone`, `clone`, `decode`, `decode`, `encode`, `encode`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Playlist>>
abstract class Playlist implements RustOpaqueInterface {
  BigInt get id;

  String get name;

  Uint64List get songIdList;

  set id(BigInt id);

  set name(String name);

  set songIdList(Uint64List songIdList);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PlaylistCollection>>
abstract class PlaylistCollection implements RustOpaqueInterface {
  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<Playlist> addPlaylist({required Playlist playlist});

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<void> addSong({required BigInt playlistId, required BigInt songId});

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<void> addToFavourites({required BigInt songId});

  Set<BigInt> get favouritesCache;

  BigInt get favouritesPlaylistId;

  Map<BigInt, Playlist> get playlistMap;

  set favouritesCache(Set<BigInt> favouritesCache);

  set favouritesPlaylistId(BigInt favouritesPlaylistId);

  set playlistMap(Map<BigInt, Playlist> playlistMap);

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<void> deletePlaylist({required BigInt playlistId});

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<Playlist> favourites();

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<List<Playlist>> getAllPlaylists();

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<Playlist> getPlaylist({required BigInt playlistId});

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<bool> isFavourite({required BigInt songId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  static Future<PlaylistCollection> newInstance() =>
      RustLib.instance.api.crateApiDataPlaylistPlaylistCollectionNew();

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<void> removeFromFavourites({required BigInt songId});

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<void> removeSong({required BigInt playlistId, required BigInt songId});

  /// DB ops go through implementation and
  /// has a hashmap for fast responses
  Future<void> renamePlaylist({
    required BigInt playlistId,
    required String newName,
  });
}
