// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:music_player/src/rust/api/error/custom_error.dart';
import 'package:music_player/src/rust/api/utils/sort_modes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `borrow_decode`, `borrow_decode`, `clone`, `clone`, `decode`, `decode`, `encode`, `encode`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Song>>
abstract class Song implements RustOpaqueInterface {
  String get album;

  String get artist;

  int? get duration;

  BigInt get id;

  PlatformInt64 get lastModifiedAt;

  String get path;

  String get title;

  set album(String album);

  set artist(String artist);

  set duration(int? duration);

  set id(BigInt id);

  set lastModifiedAt(PlatformInt64 lastModifiedAt);

  set path(String path);

  set title(String title);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SongCollection>>
abstract class SongCollection implements RustOpaqueInterface {
  Future<void> addSong({required Song song});

  Map<BigInt, Song> get songMap;

  set songMap(Map<BigInt, Song> songMap);

  static Future<Uint8List> extractAlbumArtFromFile({required String path}) =>
      RustLib.instance.api
          .crateApiDataSongSongCollectionExtractAlbumArtFromFile(path: path);

  Future<List<Song>> getAllSongs();

  Future<List<Song>> getAllSorted({required SortBy sortBy});

  Future<Song?> getSong({required BigInt id});

  factory SongCollection() =>
      RustLib.instance.api.crateApiDataSongSongCollectionNew();

  Future<void> removeSong({required BigInt id});
}
