// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:music_player/src/rust/api/data/song.dart';
part 'stream_event.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
sealed class StreamEvent with _$StreamEvent {
  const StreamEvent._();

  const factory StreamEvent.song(Song field0) = StreamEvent_Song;
  const factory StreamEvent.error(String field0) = StreamEvent_Error;
  const factory StreamEvent.done() = StreamEvent_Done;
}
