// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:music_player/src/rust/api/data/playlist.dart';
import 'package:music_player/src/rust/api/error/custom_error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `locked_playlist_collection`

Future<Playlist> addPlaylistToCollection({required String name}) => RustLib
    .instance
    .api
    .crateApiPlaylistCollectionAddPlaylistToCollection(name: name);

Future<List<Playlist>> getAllPlaylistsFromCollection() => RustLib.instance.api
    .crateApiPlaylistCollectionGetAllPlaylistsFromCollection();

Future<void> removeSongFromPlaylist({
  required BigInt songId,
  required BigInt playlistId,
}) => RustLib.instance.api.crateApiPlaylistCollectionRemoveSongFromPlaylist(
  songId: songId,
  playlistId: playlistId,
);

Future<void> addSongToPlaylist({
  required BigInt songId,
  required BigInt playlistId,
}) => RustLib.instance.api.crateApiPlaylistCollectionAddSongToPlaylist(
  songId: songId,
  playlistId: playlistId,
);

Future<void> deletePlaylist({required BigInt playlistId}) => RustLib
    .instance
    .api
    .crateApiPlaylistCollectionDeletePlaylist(playlistId: playlistId);

Future<void> renamePlaylist({
  required BigInt playlistId,
  required String newName,
}) => RustLib.instance.api.crateApiPlaylistCollectionRenamePlaylist(
  playlistId: playlistId,
  newName: newName,
);

Future<bool> isInFavourites({required BigInt songId}) => RustLib.instance.api
    .crateApiPlaylistCollectionIsInFavourites(songId: songId);

Future<void> addSongToFavourites({required BigInt songId}) => RustLib
    .instance
    .api
    .crateApiPlaylistCollectionAddSongToFavourites(songId: songId);

Future<void> removeSongFromFavourites({required BigInt songId}) => RustLib
    .instance
    .api
    .crateApiPlaylistCollectionRemoveSongFromFavourites(songId: songId);

Future<Playlist> getFavouritesFromCollection() => RustLib.instance.api
    .crateApiPlaylistCollectionGetFavouritesFromCollection();
