// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:music_player/src/rust/api/data/song.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:music_player/src/rust/api/utils/sort_modes.dart';

// These functions are ignored because they are not marked as `pub`: `locked_song_collection`

Future<void> addSongToCollection({required Song song, Uint8List? art}) =>
    RustLib.instance.api.crateApiSongCollectionAddSongToCollection(
      song: song,
      art: art,
    );

Future<List<Song>> getAllSongsFromCollection() =>
    RustLib.instance.api.crateApiSongCollectionGetAllSongsFromCollection();

Future<List<Song>> getSortedSongs({required SortBy sort}) =>
    RustLib.instance.api.crateApiSongCollectionGetSortedSongs(sort: sort);

Future<Uint8List?> getSongAlbumArt({required BigInt id}) =>
    RustLib.instance.api.crateApiSongCollectionGetSongAlbumArt(id: id);

Future<Song?> getSong({required BigInt id}) =>
    RustLib.instance.api.crateApiSongCollectionGetSong(id: id);

Future<List<Song>> getSongList({required Uint64List idList}) =>
    RustLib.instance.api.crateApiSongCollectionGetSongList(idList: idList);
