// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:music_player/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'custom_error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

@freezed
sealed class CustomError with _$CustomError implements FrbException {
  const CustomError._();

  const factory CustomError.dbError(String field0) = CustomError_DbError;
  const factory CustomError.utf8Error() = CustomError_Utf8Error;
  const factory CustomError.invalidPath(String field0) =
      CustomError_InvalidPath;
  const factory CustomError.treeError(String field0) = CustomError_TreeError;
  const factory CustomError.decodeError() = CustomError_DecodeError;
  const factory CustomError.alreadyInitialized(String field0) =
      CustomError_AlreadyInitialized;
  const factory CustomError.encodeError() = CustomError_EncodeError;
  const factory CustomError.playlistCollectionError(String field0) =
      CustomError_PlaylistCollectionError;
  const factory CustomError.albumArtError() = CustomError_AlbumArtError;
  const factory CustomError.playlistNotFound() = CustomError_PlaylistNotFound;
  const factory CustomError.unknown(String field0) = CustomError_Unknown;
}
